Unflake the plutus-extra input due to a build err
error: derivation '/nix/store/p61f2ji9kjkpmnarwj41nvyc7pdncawh-hoogle-with-packages.drv' requires non-existent output 'doc' from input derivation '/nix/store/02bvcjhr2hjyw1j7d1xigr1rjsbpz73r-flat-lib-flat-0.4.5-haddock.drv'